live_config_reload = true

[window]
startup_mode = "Fullscreen"
padding = { x = 3, y = 3 }

[mouse]
hide_when_typing = false

[cursor.style]
shape = "Beam"
blinking = "Off"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors.primary]
foreground = "#ecf9fb"
background = "#101013"
