theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
